name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Generate iOS project
        run: npx expo prebuild --platform ios --clean

      - name: Build Xcode Archive
        run: |
          cd ios
          # Tự động lấy chính xác tên Scheme đầu tiên trong Xcode
          SCHEME_NAME=$(xcodebuild -list | grep -A 1 "Schemes:" | tail -n 1 | xargs)
          echo "Dang build voi Scheme: $SCHEME_NAME"
          
          xcodebuild -workspace *.xcworkspace \
                     -scheme "$SCHEME_NAME" \
                     -configuration Release \
                     -sdk iphoneos \
                     -archivePath $PWD/build/App.xcarchive \
                     CODE_SIGNING_ALLOWED=NO \
                     archive

      - name: Export to IPA
        run: |
          mkdir -p Payload
          cp -r ios/build/App.xcarchive/Products/Applications/*.app Payload/
          zip -r App.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iPhone-App-IPA
          path: App.ipa
